# Generated by Django 5.0.6 on 2024-07-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allocation', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gpm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='scheduler.irrigationset')),
            ],
        ),
        migrations.AddField(
            model_name='irrigationset',
            name='ranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_sets', to='scheduler.ranch'),
        ),
    ]
