# Generated by Django 5.0.6 on 2024-07-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inches_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leaching_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fertilized', models.BooleanField(default=False)),
                ('fertilization_details', models.TextField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.block')),
            ],
        ),
    ]
