# Generated by Django 5.0.6 on 2024-07-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_irrigationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='inches_needed',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
