# Generated by Django 5.0.6 on 2024-07-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_block_inches_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='et_crop_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='has_crop_x',
            field=models.BooleanField(default=True),
        ),
    ]
