# Generated by Django 5.0.6 on 2024-07-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_block_et_crop_coefficient_block_has_crop_x'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('minutes_irrigated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gallons_used', models.DecimalField(decimal_places=2, max_digits=15)),
                ('acre_feet_used', models.DecimalField(decimal_places=4, max_digits=10)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_histories', to='scheduler.block')),
            ],
        ),
    ]
