# Generated by Django 5.0.6 on 2024-07-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_irrigationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='days_between_irrigations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='interval_between_irrigations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationhistory',
            name='days_between_irrigations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationhistory',
            name='interval_between_irrigations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
