# Generated by Django 5.0.6 on 2024-07-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_block_days_between_irrigations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gallons', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('acre_feet', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_meter_readings', to='scheduler.ranch')),
            ],
        ),
    ]
