# Generated by Django 5.0.6 on 2024-07-20 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_watermeterreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gpm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='scheduler.ranch')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='scheduler.well'),
        ),
        migrations.AddField(
            model_name='irrigationhistory',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_histories', to='scheduler.well'),
        ),
    ]
