# Generated by Django 5.0.6 on 2024-07-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_well_block_well_irrigationhistory_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermeterreading',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_meter_readings', to='scheduler.well'),
        ),
    ]
