# Generated by Django 5.0.6 on 2024-07-20 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_watermeterreading_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationschedule',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_schedules', to='scheduler.well'),
        ),
    ]
