# Generated by Django 5.0.6 on 2024-07-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_irrigationschedule_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationschedule',
            name='hours_needed',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
