# Generated by Django 5.0.6 on 2024-07-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_block_distribution_uniformity_block_emitter_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='distribution_uniformity',
        ),
        migrations.RemoveField(
            model_name='block',
            name='emitter_output',
        ),
        migrations.RemoveField(
            model_name='block',
            name='reference_evapotranspiration',
        ),
        migrations.RemoveField(
            model_name='block',
            name='tree_spacing',
        ),
        migrations.RemoveField(
            model_name='block',
            name='water_quality',
        ),
        migrations.AddField(
            model_name='irrigationschedule',
            name='distribution_uniformity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='irrigationschedule',
            name='emitter_output',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='irrigationschedule',
            name='reference_evapotranspiration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='irrigationschedule',
            name='tree_spacing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='irrigationschedule',
            name='water_quality',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
