# Generated by Django 5.0.6 on 2024-07-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_alter_irrigationschedule_minutes_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='inches_needed',
        ),
        migrations.RemoveField(
            model_name='irrigationschedule',
            name='emitter_output',
        ),
        migrations.RemoveField(
            model_name='irrigationschedule',
            name='inches_needed',
        ),
        migrations.RemoveField(
            model_name='irrigationschedule',
            name='tree_spacing',
        ),
        migrations.AddField(
            model_name='block',
            name='emitter_output',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='tree_spacing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='hours_needed',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
